### ISSUE TITLE
Title in activity bar  not updated when fullscreen-ing with mouse

### ISSUE THREAD

**Issue by Jehan** [deadalnix/pixel-saver#48]
If I fullscreen a window with the Super-Up shortcut or by double clicking the title bar, the activity bar is properly updated (showing the full window title).
But if I fullscreen a window by dragging its title bar to the top, the activity bar still shows the default application name.

It looks like it could be a bug in GNOME (version 3.18.2 from Fedora 23). `window.get_maximized()` in Util.getWindow() does think that the upper window is not maximized at this point. I guess it means that the signal is sent too early when the fullscreen is made by dragging with the mouse.
But I'll let you diagnose (in case I missed something) and decide if that is to be reported upstream (if you do, could you post the GNOME bug report here too please?).

Fullscreen by dragging to the top of the screen with mouse (wrong):
![screenshot from 2015-12-12 15-34-49](https://cloud.githubusercontent.com/assets/794997/11762433/0e690146-a0e6-11e5-9835-d8eaf6cd98f9.png)

Fullscreen by Super+Up or double clicking on the title bar (correct):
![screenshot from 2015-12-12 15-34-55](https://cloud.githubusercontent.com/assets/794997/11762434/0e696c30-a0e6-11e5-8bce-a4b276105bd8.png)

Thanks.

**Comment by deadalnix** [comment]
Can you confirm this is fixed ?

**Comment by Jehan** [comment]
I just uninstalled the extension and reinstalled from https://extensions.gnome.org/extension/723/pixel-saver/
The bug is not fixed. Now I have no idea if the version on extensions.gnome.org is up-to-date. Some comments from 2 weeks ago seem to say this is not in sync with your last release.

**Comment by Jehan** [comment]
Oh yeah I checked the metadata.json. Whatever version is installable from extensions.gnome.org is for GNOME shell 3.16 and 3.18 whereas I see the master version is also for 3.20. So you should update on extensions.gnome.org.

**Comment by deadalnix** [comment]
That wouldn't make a lot of sense to publish a new version without checking that bugs are fixed, would it ? So that's where we are. I want to know if the bug is fixed in master.

**Comment by deadalnix** [comment]
Can you confirm this is fixed ?

**Comment by Jehan** [comment]
I tested git master just now. It is unfortunately not fixed. Same behavior as in my initial description.

**Comment by deadalnix** [comment]
Ok thanks.

**Comment by satriani-vai** [comment]
This issue still exist

```
$ uname -a
Linux USER-PC 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 3.20.3
```

**Comment by satriani-vai** [comment]
[This fix](https://github.com/deadalnix/pixel-saver/pull/82) works great

**Comment by deadalnix** [comment]
Thanks for the update. I'm nto sure the fix work on old version of gnome, but except that, it looks good.
